version: "3.9"

services:
#  go_champ:
#    build: .
#    ports:
#      - "8080:8080"
#    volumes:
#      - .:/app

  go_db:
    container_name: go_champ_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: