services:
  go_champ:
    build: .
    depends_on:
      - go_db_champ
    ports:
      - "8080:8080"
    volumes:
      - .env:/app/.env

  go_db_champ:
    container_name: go_champ_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: